### ISSUE TITLE
Plexdrive version outdated

### ISSUE THREAD

**Issue by RaymondSchnyder** [madslundt/docker-cloud-media-scripts#21]
Hey,

Your plexdrive version is outdated, as of the first of august, the newest version is 5.0.0 and that version replaced mongodb with boltdb (single file)

Now the cache file with boltdb is attached like this "--cache-file /path/to/cache-file"

Ive made a fork to all this, and made it to work with the new plexdrive version, you can look at it if you want to, keep in mind tho that my fork just "works" its not bug free i think

**Comment by madslundt** [comment]
Yes I'm aware of that. The problem I have with Plexdrive 5.0.0 is that it only caches in memory.
I don't think it is the best solution when it comes to media cache. You don't need the speed from memory when it's just media. I prefer caching a lot of media on disk rather than in memory.

However good job on Plexdrive 5.0.0

**Comment by RaymondSchnyder** [comment]
@madslundt
I have a little question, on Plexdrive 4, do you also have issues with deleting remote folders? I cant delete any folders on 5.
