### ISSUE TITLE
Plans for Plexdrive 5.x?

### ISSUE THREAD

**Issue by lhilton** [madslundt/docker-cloud-media-scripts#31]
I am curious if there are plans for updating this to Plexdrive v5? I've had quite noticeably improved performance and lower memory consumption on the 5.x release.

If you don't have plans, would there be a willingness to merge my PR if I did the work?

**Comment by madslundt** [comment]
The reason why I chose Plexdrive v4 was that it cache data to a disk and not memory. In Plexdrive v5 there is no option to store cached data in anything else than memory.

However I could create a branch with Plexdrive v5 if that's fine with you.

**Comment by lhilton** [comment]
In v5 you control RAM consumption using the `--chunk-size` and `--max-chunks` parameter. Do you normally find that v4 eats as much RAM as it can then? Right now that's my experience with it.

It sounds like v4 might be well suited for different use cases that v5 then, a different branch would make the most sense. I'll spend some time looking to see how we might best deal with the configuration differences between the two under the idea that they should both be alive and reasonably easy to maintain.

**Comment by madslundt** [comment]
Yeah I know that. The problem is that I like to have a lot of cache on my machine to allow multiple streams and keep the buffering as low as possible. Right now I'm caching roughly 4 TB.
In my point of view Plexdrive v4 is better for media streaming than Plexdrive v5 because streaming huge files can only be cached limited. Imagine you are streaming a 4k media that has a total size of +50GB. That would require a lot of RAM if you want to cache the whole file into memory.

However that is just my point of view and for some people Plexdrive v5 works just fine.

Yeah a new branch or a parameter set to use Plexdrive v5.
