### ISSUE TITLE
So ideas

### ISSUE THREAD

**Issue by Admin9705** [madslundt/docker-cloud-media-scripts#7]
So what you have looks promising (added a star to yours).  I want to try to fit that in.  I dockered the entire plex server including programs except the rclone portion.  I'm running into the rclone ban issue.  If you have a second, take a look and let me know what you think:

https://github.com/Admin9705/The-Awesome-Plex-Server

I'll look into your docker and see how I can squeeze into it.  Server setup works great.  Running with 147TB with a duo xeon and 0 issues with constant downloads.

Added your link to the page also

**Comment by madslundt** [comment]
I agree it would fit perfectly in. You are you using docker for everything except Rclone and Plexdrive as I see it.

Very well written guide by the way!

Let me know if you need any help.

**Comment by madslundt** [comment]
Yes I'm using PD4. Haven't really tried with PD5 because of the memory cache.

I can only get it to work with :shared. Without :shared I can't access the folder outside the container.
Did you add `--privileged --cap-add=MKNOD --cap-add=SYS_ADMIN --device=/dev/fuse` as well?

Okay I haven't had problems waiting for Rclone, it is mostly waiting for Plexdrive that is the problem. Specially if it's the first time Plexdrive starts without cache.
Yes correct. I use sleep to wait for the paths to show some data.

**Comment by Admin9705** [comment]
Ya, avoid PD5.  It will just stop working if you have large scans going on.  No, I haven't tried it those solutions, but will look into it.  Makes sense with what your doing.  I'll have to examine your scripts more.  Overtime, would love to take what I have, what you have an just make it an easy solution.  Plex Cloud drove me so mad, it made me do this lol.  0 linux experience 4 months ago.  I can tell your well ahead.

**Comment by Admin9705** [comment]
Posted your project if someone wants to work on futurewise, if I have the time or someone gets working; well let you know (created a reddit finally): https://www.reddit.com/r/AwesomePlex/
